{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf200
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\csgray\c0;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf2 \CocoaLigature0 proj3: program.o bigint.o bigint.h\
        g++ -std=c++11 -o proj3 program.o bigint.o\
\
program.o: program.cpp bigint.h\
        g++ -std=c++11 -c program.cpp\
\
bigint.o: bigint.cpp bigint.h\
        g++ -std=c++11 -c bigint.cpp\
\
clean:\
        rm *.o proj3\
}