---
title: "Ch2 HW"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = TRUE}

packages <- c('PropCIs', 'epitools')
lapply(X = packages, FUN = install.packages)
lapply(X = packages, FUN = library, character.only = TRUE)

```

Question 6 a

Compare proportions for the categories *unintentional* and *terrorism* by a difference and by a ratio.

```{r, echo = TRUE}

# Original count data
gunshot_counts <- list(
  assault = 179793,
  unintentional =  65502,
  suicide = 24624, 
  undetermined = 17401,
  law_enforcement = 5266,
  terrorism = 10
)

# Variables
n <- sum(unlist(x = gunshot_counts, use.names = FALSE))
unintentional <- as.integer(x = gunshot_counts['unintentional'])
terrorism <- as.integer(x = gunshot_counts['terrorism'])

# Contingency table
gunshot_ct <- matrix(
  data = c(unintentional, n - unintentional,
           terrorism, n - terrorism),
  nrow = 2, 
  byrow = TRUE
)

print(gunshot_ct)

# Difference of proportions tests
cat('\nDifference of proportions using prop.test:\n')
prop.test(
  x = gunshot_ct,
  conf.level = 0.95,
  alternative = 'two.sided',
  correct = FALSE
)

cat('\nDifference of proportions using diffscoreci:\n')
diffscoreci(
  x1 = unintentional,
  n1 = n,
  x2 = terrorism,
  n2 = n,
  conf.level = 0.95
)

# Risk score tests
cat('\nRisk score:\n')
riskscoreci(
  x1 = unintentional,
  n1 = n,
  x2 = terrorism,
  n2 = n,
  conf.level = 0.95
)

```

Question 6 b

```{r, echo = TRUE}

# Odds ratio manually
pi_democrat_liberal <- 0.89
odds_democrat_liberal <- pi_democrat_liberal / (1 - pi_democrat_liberal)
pi_rep_con <- 0.22
odds_rep_con <- pi_rep_con / (1 - pi_rep_con)
odds_ratio <- odds_democrat_liberal / odds_rep_con

# Contingency table
political_ct <- matrix(
  data = c(pi_democrat_liberal, 1 - pi_democrat_liberal,
          pi_rep_con, 1 - pi_rep_con) * 100,
  nrow = 2,
  byrow = TRUE
)

print(political_ct)    

cat('\nOdds ratio manually:\n', odds_ratio, '\n')

# Odds ratio with oddsratio function
cat('\nOdds ratio with epitools oddsration function:\n')
oddsratio(
    x = c(pi_democrat_liberal, 1 - pi_democrat_liberal,
          pi_rep_con, 1 - pi_rep_con) * 100,
    method = 'wald',
    conf=0.95,
    correct=FALSE
)

```

Question 12.

```{r, echo = TRUE}

# Odds ratio manually
pi_white_white <- 0.93
odds_white_victim <- pi_white_white / (1 - pi_white_white)
pi_black_black <- 0.92
odds_black_victim <- (1 - pi_black_black) / pi_black_black
odds_ratio <- odds_white_victim / odds_black_victim

# Contingency table
crime_ct <- matrix(
  data = c(pi_white_white, 1 - pi_black_black,
          1 - pi_white_white, pi_black_black) * 100,
  nrow = 2,
  byrow = TRUE
)
print(crime_ct)

cat('\nOdds ratio manually:\n', odds_ratio, '\n')

# Odds ratio with oddsratio function
cat('\nOdds ratio with epitools oddsration function:\n')
oddsratio(
    x = crime_ct,
    method = 'wald',
    conf=0.95,
    correct=FALSE
)

```
Question 16

```{r, echo = TRUE}
pchisq(q = 73.4, df = 8, lower.tail = FALSE)

```
