---
title: "Ch10 HW"
author: "Caijun Qin"
date: "12/2/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

Install packages
```{r pressure, echo=FALSE}

packages <- c('lme4', 'reshape2', 'splitstackshape')
install.packages(packages)
lapply(packages, library, character.only = TRUE)

```

Question 4

load data

```{r pressure, echo=FALSE}
# A for Alcohol
# C for Cigarettes
# M for Marijuana

Input="
alcohol cigarettes marijuana count  
yes yes yes 911
yes yes no 538
yes no yes 44
yes no no 456
no yes yes   3
no yes no 43
no no yes 2
no no no 279
"
sub=read.table(textConnection(Input),header=T)
n=sum(sub$count)

sub_melt=melt(sub,id.vars = "count")
sub_melt=as.data.frame(sub_melt)

long.sub=expandRows(sub_melt,"count")
long.sub$subject=rep(1:n,times=3)

# sort dataframe by subject rather than variable
long.sub=long.sub[order(long.sub$subject),]

dimnames(long.sub)[[2]]=c("Substance","Use","Student")

head(long.sub)
tail(long.sub)

```

Part A

```{r pressure, echo=FALSE}

fit <- lme4::glmer(
  formula = ifelse(test = Use == 'yes', yes = 1, no = 0) ~ (1 | Student) + factor(x = Substance, levels = c('cigarettes', 'alcohol', 'marijuana')),
  data = long.sub,
  family = binomial(link = 'logit')
)
summary(fit)

fit.null <- lme4::glmer(
  formula = ifelse(test = Use == 'yes', yes = 1, no = 0) ~ (1 | Student),
  data = long.sub,
  family = binomial(link = 'logit')
)

anova(fit, fit.null)
lmtest::lrtest(fit, fit.null)

```

load data

```{r pressure, echo=FALSE}

Input="
 A C M R G count
 1 1 1 1 1 405 
 1 1 2 1 1 268 
 1 1 1 1 2 453 
 1 1 2 1 2 228
 1 1 1 2 1  23 
 1 1 2 2 1  23 
 1 1 1 2 2  30 
 1 1 2 2 2  19
 1 2 1 1 1  13 
 1 2 2 1 1 218  
 1 2 1 1 2  28 
 1 2 2 1 2 201
 1 2 1 2 1   2 
 1 2 2 2 1  19 
 1 2 1 2 2   1 
 1 2 2 2 2  18
 2 1 1 1 1   1 
 2 1 2 1 1  17 
 2 1 1 1 2   1 
 2 1 2 1 2  17
 2 1 1 2 1   0 
 2 1 2 2 1   1 
 2 1 1 2 2   1 
 2 1 2 2 2   8
 2 2 1 1 1   1 
 2 2 2 1 1 117 
 2 2 1 1 2   1 
 2 2 2 1 2 133
 2 2 1 2 1   0 
 2 2 2 2 1  12 
 2 2 1 2 2   0 
 2 2 2 2 2  17
"

sub1=read.table(textConnection(Input),header=T)
sub1$A=factor(sub1$A,levels=1:2,labels=c("yes","no"))
sub1$C=factor(sub1$C,levels=1:2,labels=c("yes","no"))
sub1$M=factor(sub1$M,levels=1:2,labels=c("yes","no"))
sub1$R=factor(sub1$R,levels=1:2,labels=c("white","other"))
sub1$G=factor(sub1$G,levels=1:2,labels=c("female","male"))

sub1_melt=melt(sub1,id.vars = c("R","G","count"))
sub1_melt=as.data.frame(sub1_melt)

long.sub1=expandRows(sub1_melt,"count")
long.sub1$subject=rep(1:n,times=3)

# sort dataframe by subject rather than variable
long.sub1=long.sub1[order(long.sub1$subject),]

dimnames(long.sub1)[[2]]=c("Race","Gender","Substance","Use","Student")
levels(long.sub1$Substance)=c("alcohol","cigarettes","marijuana")

head(long.sub1)
tail(long.sub1)

```

```{r pressure, echo=FALSE}

fit1 <- lme4::glmer(
  formula = ifelse(test = Use == 'yes', yes = 1, no = 0) ~ (1 | Student) + factor(x = Substance, levels = c('cigarettes', 'alcohol', 'marijuana')) + Race + Gender,
  data = long.sub1,
  family = binomial(link = 'logit')
)

summary(fit1)

```

```{r pressure, echo=FALSE}

 (2, 4, 1, 3, 3, 5, 4, 2, 3, 1)

```

```{r pressure, echo=FALSE}

```

```{r pressure, echo=FALSE}

```

