---
title: "R Notebook"
output: html_notebook
---

4.1 Basic Math
```{r}

1 + 1
1 + 2 + 3
3 * 7 * 2
4 / 2
4 / 3
4 * 6 + 5
(4 * 6) + 5
4 * (6 + 5)

```

4.2 Variables
4.2.1 Variable Assignment
```{r}

x <- 2
x
y = 5
y
3 -> z
z
a <- b <- 7
a
b
assign("j", 4)
j

```

4.2.2 Removing Variables
```{r}

j
rm(j)
j

```

```{r}
# variable names are case-sensitive

apple <- 4
apple
APPLE
```

4.3 Data Types

```{r}

x <- 12
class(x)
y <- 4.22
class(y)
charVar <- 'c'
class(charVar)
stringVar <- "string"
class(stringVar)

```

4.3.1
```{r}

is.numeric(x=x)
i <- 5L
i
is.integer(x=i)
is.numeric(x=i)
class(x=4L)
class(x=2.8)
4L * 2.8
class(x=5L)
class(x=2L)
5L / 2L
class(x=5L / 2L)

```

4.3.2 Character Data

```{r}

# character is the same as string
x <- "data"
x
y <- factor(x="data")
y

nchar(x=x)
nchar(x="hello")
nchar(x=3)
nchar(x=456)
nchar(x=y)

```

4.3.3 Dates
```{r}

date1 <- as.Date(x="2020-05-28")
date1
class(x=date1)
as.numeric(x=date1)

date2 <- as.POSIXct("2020-12-25 12:00")
date2
class(x=date2)
as.numeric(x=date2)

```

4.3.4 Logical
```{r}

TRUE * 5
FALSE * 5
k <- TRUE
class(x=k)
is.logical(x=k)

# T / F are shortcuts for TRUE / FALSE
T
F
class(x=T)
T <- 7
class(x=T)

# logical values from comparisons
2 == 3
2 != 3
2 < 3
2 <= 3
2 > 3
2 >= 3
"data" == "stats"
"data" < "stats"

```

4.4 Vectors
4.4.1 Vector Operations
```{r}

x <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
x
x * 3
x + 2
x - 3
x / 4
x ^ 2
sqrt(x=x)

```

```{r}

# building vectors from range
1:10
10:1
-2:3
5:-7

```

```{r}

# operations between vectors
x <- 1:10
y <- -5:4
x + y
x - y
x * y
x / y
x ^ y
length(x=x)
length(x=y)
length(x=x+y)

```

```{r}

# recycling vector operations
x + c(1, 2)
x + c(1, 2, 3)

```

```{r}

# comparisons with vectors
x <= 5
x > y
x < y

x <- 10:1
y <- -4:5
any(x < y)
all(x < y)

```

```{r}

# nchar represents each element in vector
q <- c("Hockey", "Football", "Baseball", "Curling", "Rugby", "Lacrosse", "Basketball", "Tennis", "Cricket", "Soccer")
nchar(x=q)
nchar(x=y)

```

```{r}

# accessing elements; note that R has 1-based index and inclusive at both ends
x
x[1]
x[1:2]
x[c(1, 4)]

```

```{r}

# named vectors
c(one="a", two="y", three="z")
w <- 1:3
names(x=w) <- c("a", "b", "c")
w

```

4.4.2 Factor Vectors
```{r}

q2 = c(q, "Hockey", "Lacrosse", "Hockey", "Water Polo", "Hockey", "Lacrosse")
q2Factor <- as.factor(x=q2)
q2Factor
as.numeric(q2Factor)
factor(x=c("High School", "College", "Masters", "Doctorate"),
    levels=c("High School", "College", "Masters", "Doctorate"),
    ordered=TRUE)

```


4,5 Calling Functions
```{r}

# example
x
mean(x=x)

```

4.6 Function Documentation
```{r}

# displays documentation for operators
?`+`
?`*`
?`==`

# search all functions with given substring
apropos(what="mea", where=FALSE, ignore.case=TRUE, mode="any")


```

4.7 Missing Data
4.7.1 NA
```{r}

# missing values that show up in vectors
z <- c(1, 2, NA, 8, 3, NA, 3)
is.na(x=z)

zChar <-c("Hockey", NA, "Lacrosse")
zChar
is.na(x=zChar)

```

4.7.2 NULL
```{r}

# NULL does not indicate missing value, but rather nothingness and cannot exist inside vectors
z <- c(1, NULL, 3)
z

d <- NULL
d
is.null(x=d)

7
is.null(x=7)

```
